# Generated by Django 3.2 on 2023-10-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20231012_0819'),
        ('subtasks', '0002_subtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='team',
        ),
        migrations.AddField(
            model_name='subtask',
            name='team',
            field=models.ManyToManyField(related_name='subtasks', to='teams.Team'),
        ),
    ]
