# Generated by Django 3.2 on 2023-10-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtasks', '0003_auto_20231012_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='completed_data',
            new_name='completed_date',
        ),
    ]
