# Generated by Django 3.2 on 2023-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_data', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
