# Generated by Django 3.2 on 2023-10-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='completed_data',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='team',
            name='modified_at',
        ),
    ]
