# Generated by Django 3.2 on 2023-10-13 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_auto_20231013_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
