# Generated by Django 3.2 on 2023-10-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20231013_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
    ]
