# Generated by Django 3.2 on 2023-10-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_user',
            new_name='create_user',
        ),
    ]
