# Generated by Django 3.2 on 2023-10-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_created_user_task_create_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed_data',
            new_name='completed_date',
        ),
    ]
